FONAShop/graceShopper

- .travis.yml
- package.json
---
Updated package.json and travis.yml
> updated package.json and travis.yml

- server/db/models/review.js
> Added review model

- server/api/index.js
- server/api/products.js
- server/db/models/index.js
- server/db/models/product.js
> Product model 09

- package-lock.json
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/product.js
- server/index.js
> Associations added and order model created

- client/app.js
- client/components/AllProducts.js
- client/components/index.js
- client/routes.js
- public/style.css
---
Add AllProducts presentational component with flexbox styling
> All products issue 10

- script/seed.js
added seed data for products and added more users
> added seed data for products and added more users

- client/components/AllProducts.js
- client/routes.js
- client/store/index.js
- client/store/product.js
---
- Added store for all products
- Actions for get all product | one product | remove product
- reducer (for 3 cases)
- changed dumb component AllProducts
- AllProducts component connected to store
> added store for All Products and the connect Container

- client/components/checkout.js
I built out some of the basic parts of the checkout component. A lot more needs to be done.
> Built some of the checkout component

- client/components/Cart.js
- client/components/index.js
- client/routes.js
> created a sample cart component, will need to add thunk

- script/seed.js
- server/db/models/index.js
- server/db/models/orderProduct.js
- server/db/models/product.js
- server/index.js
Implemented suggestions from code review
> Addressing code review 28

- client/components/navbar.js
- public/style.css
---
-updatet the nav bar
-added Link to all products
-added filter bar
> Update the navbar issue 18

- server/api/cart.js
- server/api/index.js
- server/index.js
Implement the cart session store
> Cart backend 19

- client/store/cart.js
- client/store/index.js
---
The cart redux actions, thunks, action creators, and reducers built out
> Cart redux issue #24

- client/components/AllProducts.js
- client/components/SingleProduct.js
- client/components/index.js
- client/routes.js
- client/store/product.js
Changes made: 
Refactored store/product
-allProducts 
-selectedProducts
Created a SingleProducts component
> Create single product comp 34

- client/components/AllProducts.js
- client/components/Cart.js
- client/components/Product.js
- client/components/SingleProduct.js
- server/db/models/product.js
- display products on the cart page
> Cart component 20

- server/auth/google.js
Simply removed unnecessary comments and slacked out API keys and credentials to team members.
> added API keys to enable OAuth

- client/components/Cart.js
- client/components/Product.js
- client/store/product.js
- script/seed.js
- server/db/models/product.js
- changed the price in the seed file (need to run 'npm run seed' after merged)
- save price as integer to db (e.g. 5 => 500)
- get price as string from db (e.g. 500 => 5.00)
> Fixed the price number

- client/components/Reviews.js
- client/components/SingleProduct.js
- client/components/index.js
- client/socket.js
- client/store/index.js
- client/store/reviews.js
- script/seed.js
- server/api/index.js
- server/api/reviews.js
- server/db/models/index.js
- server/db/models/review.js
- server/index.js
- server/socket/index.js
- guests can see the reviews 
- users can see and post reviews
- socket.io integration
> Product review component

- client/components/Cart.js
- client/components/checkout.js
- client/store/index.js
- client/store/order.js
- server/api/checkout.js
- server/api/index.js
- server/db/models/order.js
> Checkout submit issue #39

- client/components/Cart.js
- client/components/checkout.js
- client/components/user-home.js
- client/store/cart.js
- client/store/order.js
- package.json
- server/api/checkout.js
Redirected to users home page after checkout, fixed the api/checkout promise logic, and cleared the cart after checkout
> Fixed api/checkout promise logic, redirected to users page, cleared the cart

- client/components/navbar.js
- client/store/order.js
Added fetchCart after submittal on checkout page, also edited Navbar title, and deleted navbar activeclassname=selected
> Added fetchCart after submittal on checkout page, also edited Navbar

- client/components/Cart.js
- client/components/index.js
- client/store/cart.js
- client/store/user.js
- server/api/cart.js
- server/auth/index.js
- server/db/models/cart.js
- server/db/models/cartProduct.js
- server/db/models/index.js
- server/index.js
Edits in this pull request:
- removed double quotes,
- added cartProducts through table, 
- saves cart data on log out,
- successfully persisted cart for logged in users
> Persistent cart 52

- client/store/cart.spec.js
- server/api/cart.js
> Tests for the cart store

- client/socket.js
> fixed socket test issue

- client/store/order.js
- package-lock.json
- package.json
- public/index.html
Added toast notification after checkout submittal
> Toastr issue #81

- script/seed.js
> Update seed file 84

- client/components/AllProducts.js
- client/components/Cart.js
- client/components/Reviews.js
- client/components/SingleProduct.js
- client/components/auth-form.js
- client/components/checkout.js
- updated cart and checkout style
> Semantic Ui for cart and checkout

- client/components/Product.js
- client/components/SingleProduct.js
> Display categories
